# Generated by Django 3.0.7 on 2020-06-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorten',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
