# Generated by Django 3.0.7 on 2020-06-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorten', '0002_auto_20200615_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorten',
            name='sorturl',
        ),
    ]
