# Generated by Django 3.0.7 on 2020-06-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorten', '0002_sorten_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorten',
            name='responseurl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sorten',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
