# Generated by Django 3.0.7 on 2020-06-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorten', '0002_sorten_shorturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorten',
            name='random_int',
        ),
        migrations.AlterField(
            model_name='sorten',
            name='shorturl',
            field=models.CharField(max_length=200),
        ),
    ]
